spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/media
    username: media
    password: qwe123

logging:
  config: classpath:logback-production.xml

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always